image: hasanalperen/dgk

stages:
    - test
    - build_app
    - build_image

variables:
    CONTAINER_IMAGE: $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
    REGISTRY_USER: "YOUR_GITHUB_USER"
    REGISTRY_PASSWORD: "YOUR_GITHUB_PASSWORD"
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
    SVC_PORT: 8081
    IMAGE_REPO: "$REGISTRY_USER/$CI_PROJECT_NAME"
    APP_NAME: backend

before_script:
    - echo $CONTAINER_IMAGE

lint_test:
    stage: test
    script:
        - echo "lint test OK"
    tags:
        - be

maven_test:
    image: adoptopenjdk/maven-openjdk11
    stage: test
    script:
        - mvn clean verify
    tags: 
        - be

build_app:
    image: adoptopenjdk/maven-openjdk11
    stage: build_app
    artifacts:
        paths:
            - target/todo-backend.jar
    script: 
        - echo "java build"
        - mvn clean package
    tags:
        - mvn

build_image:
    image: docker
    services: 
        - name: docker:20-dind
          alias: docker
          command: ["--tls=false"]
    stage: build_image
    script:
        - sleep 5
        - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
        - ls target/
        - docker build -t $REGISTRY_USER/$CONTAINER_IMAGE .
        - docker push $REGISTRY_USER/$CONTAINER_IMAGE
        - rm -rf /var/run/docker.sock
    tags: 
        - be
